### ISSUE TITLE
Please add your avatar to this repo

### ISSUE THREAD

**Issue by gxres042** [HackerRouter/HackerRouter.github.io#1]
如题
要加头像的代码真的很难改的啊 q_q

**Comment by HackerRouter** [comment]
没事，我下个月有空整整博客把头像资源加了
到时候通知你

**Comment by HackerRouter** [comment]
> 

http://unityterminal.one/StreamingAssets/avatar.png
安排上了
博客目前换成了临时demo版，可以去看看（
webgl的适配搞得我吐血

**Comment by gxres042** [comment]
好事！
WebGL 确实有点怪，尝试输了点内容结果就飞走了（指位置变更）
话说你现在用的什么解析啊，可以考虑上一个 SSL 开 HTTPS（

**Comment by HackerRouter** [comment]
寄 为啥我头像还是不能正常显示啊
我博客直接万众瞩目了（因为显示不出的头像

看你dc（虽然我不知道你会先看github还是先看dc

**Comment by HackerRouter** [comment]
我博客直接万众瞩目了（因为显示不出的头像

**Comment by gxres042** [comment]
> 寄 为啥我头像还是不能正常显示啊

hmmm 会不会浏览器没检测到有 SSL 立刻给你拦下来了

**Comment by HackerRouter** [comment]
实时回复是吧（
丢到了图床：https://s3.bmp.ovh/imgs/2022/07/31/4fe6c3dcb1e22f82.png
再试逝？

**Comment by HackerRouter** [comment]
对了看眼你dc（帮个忙

**Comment by gxres042** [comment]
> 对了看眼你dc（帮个忙

dc 好久没看了......我上去看一下
